version: "3.7"

################################################################################
# NETWORKING CONFIGURATION
################################################################################

networks:
    adjuftments:
        driver: bridge

################################################################################
# SERVICES CONFIGURATION
################################################################################

services:

    ####################################
    # POSTGRES DATABASE
    ####################################

    database:
        container_name: postgres
        image:          postgres:13.1
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_DB}
            - ALLOW_IP_RANGE="0.0.0.0/0"
            - TZ=UTC
            - PG_TZ=UTC
        volumes:
            - ${DOCKER_DIRECTORY}/postgres/:/var/lib/postgresql/data
        logging:
            options:
                max-size: 10m
                max-file: "3"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout:  5s
            retries:  5
        restart:        unless-stopped
        networks:
            adjuftments: null
        ports:
            - "5432:5432"

    ####################################
    # FLASK WEBSERVER
    ####################################

    webserver:
        container_name: webserver
        build:
            context:    ${DOCKER_DIRECTORY}/build/
            dockerfile: Dockerfile
        networks:
            adjuftments: null
        ports:
            - "5000:5000"
        volumes:
            - ${DOCKER_DIRECTORY}/:/home/adjuftments_v2/
        restart:        ${UNIVERSAL_RESTART_POLICY}
        depends_on:
            - database
        labels:
            traefik.enable: false
        environment:
            FLASK_APP:          "/home/adjuftments_v2/adjuftments_v2/views.py"
            FLASK_ENV:          "development"
            DOCKER_ENVIRONMENT: "True"
        working_dir:    /home/adjuftments_v2/adjuftments_v2
        command:        flask run --host=0.0.0.0

    ####################################
    # ADJUFTMENTS AIRTABLE EXECUTOR
    ####################################

    adjuftments:
        container_name: adjuftments
        build:
            context:    ${DOCKER_DIRECTORY}/build/
            dockerfile: Dockerfile
        networks:
            adjuftments: null
        volumes:
            - ${DOCKER_DIRECTORY}/:/home/adjuftments_v2/
        restart:        on-failure
        depends_on:
            - database
            - webserver
        labels:
            traefik.enable: false
        working_dir:    /home/adjuftments_v2/
        command:
            - /home/adjuftments_v2/build/wait-for-postgres.sh
            - /home/adjuftments_v2/scripts/run_adjuftments.py
        environment:
            TZ:                 ${TZ}
            DOCKER_ENVIRONMENT: "True"

    ####################################
    # ADJUFTMENTS JOB SCHEDULER
    ####################################

    job_scheduler:
        container_name: job_scheduler
        build:
            context:    ${DOCKER_DIRECTORY}/build/
            dockerfile: Dockerfile
        networks:
            adjuftments: null
        volumes:
            - ${DOCKER_DIRECTORY}/:/home/adjuftments_v2/
        restart:        on-failure
        depends_on:
            - database
            - webserver
            - adjuftments
        labels:
            traefik.enable: false
        working_dir:    /home/adjuftments_v2/
        command:
            - /home/adjuftments_v2/build/wait-for-postgres.sh
            - /home/adjuftments_v2/scripts/run_scheduler.py
        environment:
            TZ:                 ${TZ}
            DOCKER_ENVIRONMENT: "True"